### ISSUE TITLE
Error copying file: %s [Errno 13] Permission denied: './ChangeLog'

### ISSUE THREAD

**Issue by jurobystricky** [clearlinux/autospec#253] opened 2018-09-17 17:16 UTC
Running autospec can generate the following error:
Error copying file: %s [Errno 13] Permission denied: './ChangeLog'

This seems to be the case when the file ./ChangeLog already exists.

**Comment by phmccarty** [comment] 2019-01-18 21:47
@jurobystricky Did you by chance happen to run autospec as root, and then later as non-root? Autospec does a `shutil.copy` to copy the changelog file from the source tarball to the package git repo, so the file is simply overwritten unless an unexpected error occurs (`EPERM` is this case). Has the issue recurred for you?

**Comment by jurobystricky** [comment] 2019-01-18 22:05
It's been a while, but it is almost certainly the case. We used to run as root at that time on occasions. (AFAIK our mock was not setup properly, so we had to run sudo make build, or something like that)

**Comment by phmccarty** [comment] 2019-01-18 22:48
Okay, thanks. I think we should close this, since (as far as I can tell), autospec raising this error and exiting early is for the best. It is an unexpected error condition, and we definitely want new ChangeLog entries to be written when possible, since they are later committed by autospec too.

**Comment by phmccarty** [comment] 2019-02-07 19:46
I just reproduced this issue. Investigating.

**Comment by phmccarty** [comment] 2019-02-07 20:16
After further investigation, I was able to reproduce the issue only because the ChangeLog file in my local package git repo had 444 permissions. Though according to git, the permissions were supposed to be 644, confirmed by freshly cloning the git repo in question. Git does not detect when file perms change from 644->444.

Thus, because the target file had 444 permissions, autospec's attempted overwrite of it raised a "permission denied" error.

After the fix from #307, I'm not convinced that autospec should behave any differently in this case. I had built this package a few months ago, and at that time, the file must have been written with 444 permissions.

If anyone else encounters this issue when using autospec, run `chmod 644 ChangeLog` and retry, and make sure your autospec has the fix from #307.

**Closed by phmccarty** 2019-02-07 20:16 UTC
