### ISSUE TITLE
Mariadb and postgres build failed.

### ISSUE THREAD

**Issue by LiuBijun** [clearlinux/autospec#505] opened 2019-10-18 03:05 UTC
OS: Clear Linux 31300
After I modify the option.conf file to enable avx512 (set use_avx512 = true), I run 'make autospec'.
It outputs error logs.
_**Unknown pattern match:  Java
Unknown pattern match:  JNI

total tests: 0
total passing: 0
[FATAL] Build failed, aborting
make: *** [../common/Makefile.common:165: autospec] Error 1**_

**Comment by phmccarty** [comment] 2020-01-07 02:50
Hi @LiuBijun, there is not enough information in your bug report to determine what the root cause might be. Can you check the log files from the `results/` directory for hints about the source of the error?

**Comment by phmccarty** [comment] 2020-04-15 22:57
Since I have not seen any issues with mariadb or postgresql builds, I am closing this.

If you are still encountering problems with a package build, feel free to open a new issue.

**Closed by phmccarty** 2020-04-15 22:57 UTC
Labels: need info
